apiVersion: v1
kind: ServiceAccount
metadata:
  name: henri
# nexus-registry-secret must exist in the target namespace.
# It provides credentials to pull images from main.repository.ext.icrc.org.
imagePullSecrets:
  - name: nexus-registry-secret
